name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: SegoeUI
      fonts:
        - asset: fonts/Segoe-UI.ttf
        - asset: fonts/Segoe-UI-Bold.ttf
        - asset: fonts/Segoe-UI-Italic.ttf
        - asset: fonts/Segoe-UI-Bold-Italic.ttf
  assets:
    - assets/images/lines/top.svg
    - assets/images/lines/jug.svg
    - assets/images/lines/mid.svg
    - assets/images/lines/bot.svg
    - assets/images/lines/sup.svg
    - assets/images/player_background.svg
    - assets/images/map.jpg
    - assets/images/champion_icon.jpg
    - assets/images/champion_icon2.png
    - assets/images/champions/TOP/
    - assets/images/champions/JUG/
    - assets/images/champions/MID/
    - assets/images/champions/BOT/
    - assets/images/champions/SUP/


